### PR TITLE
PARQUET-1123: [C++] Update parquet-cpp to use Arrow's AssertArraysEqual

### PR DESCRIPTION
**Pull request by cpcloud**

### CODE REVIEW

**Comment by cpcloud** [comment]
Alternatively we can put the parquet version into a namespace. It seems like makes more sense to have one place for this function though.

**Comment by wesm** [comment]
Yeah, not ideal. Can you put the function in an anonymous namespace and then we'll remove after 1.3.1 goes out?

**Comment by cpcloud** [comment]
Yep.

**Comment by cpcloud** [comment]
@wesm I couldn't get this to compile with an anonymous namespaces, so I used the fully qualified version. Is there some incantation to make this compile with an anonymous namespace that I'm missing?

**Comment by wesm** [comment]
ah, I guess not, I am not an expert in symbology with anonymous namespaces

**Comment by wesm** [comment]
You can just use `internal` or `detail` namespace then

**Comment by cpcloud** [comment]
Passing on Travis: Appveyor build is here: https://ci.appveyor.com/project/cpcloud/parquet-cpp/build/1.0.36

**Comment by cpcloud** [comment]
Hm this doesn't appear to be passing on my fork though.

**Comment by cpcloud** [comment]
Looks unrelated to my changes: https://travis-ci.org/cpcloud/parquet-cpp/jobs/284733236

**Comment by cpcloud** [comment]
@wesm This is now passing on Appveyor: https://ci.appveyor.com/project/cpcloud/parquet-cpp/build/1.0.36

**Comment by wesm** [comment]
+1

**Pull request closed without merging**
