### PR TITLE
PARQUET-2467: Archive this repo

### PR DESCRIPTION
**Pull request by xhochy**
As this repository has been unused for over six years now, I would go ahead archive its contents.

### CODE REVIEW

**Comment by wesm** [comment]
+1

**Comment by xhochy** [comment]
Filed PARQUET-2467

**Comment by wgtmac** [comment]
I have filed https://issues.apache.org/jira/browse/INFRA-25766 to see if the infra team can directly archive this repo like https://github.com/cmu-db/peloton.

**Comment by xhochy** [comment]
I would first merge this PR, though. OK with that @wgtmac ?

**Comment by wgtmac** [comment]
Sounds good!

**Pull request merged**
