### PR TITLE
PARQUET-463: Add local DCHECK macros, fix some dcheck bugs exposed

### PR DESCRIPTION
**Pull request by wesm**
I was also able to remove the `-Wno-unused-value` compiler flag. Removing `-Wno-unused-variable` will have to take place in another patch (more work required).

### CODE REVIEW

**Comment by wesm** [comment]
green build: https://travis-ci.org/wesm/parquet-cpp/builds/112673546

**Comment by wesm** [comment]
rebasing now

**Comment by julienledem** [comment]
+1

**Comment by wesm** [comment]
Rebased. Will post a green build when I have one

**Comment by wesm** [comment]
green build: https://travis-ci.org/wesm/parquet-cpp/builds/112738155

**Comment by wesm** [comment]
thank you!

**Pull request closed without merging**
