### PR TITLE
PARQUET-1043: Raise minimum CMake version to 3.2, delete cruft. 

### PR DESCRIPTION
**Pull request by wesm**
Also fixes a gcc 4.8 buglet (std::vector::erase does not accept a const_iterator in gcc 4.8)

### CODE REVIEW

**Comment by wesm** [comment]
Appveyor build for this one https://ci.appveyor.com/project/wesm/parquet-cpp/build/1.0.32

**Comment by wesm** [comment]
@majetideepak is this ok with you?

**Comment by cpcloud** [comment]
LGTM +1

**Comment by wesm** [comment]
OK, merging this for now since I'm going to do some more work on the build system after ARROW-1142 goes in

**Comment by majetideepak** [comment]
Sorry, I was traveling the whole of last week.
This is okay with me. Thanks!

**Pull request closed without merging**
