### PR TITLE
PARQUET-1038: Key value metadata should be nullptr if not set

### PR DESCRIPTION
**Pull request by cpcloud**

### CODE REVIEW

**Comment by wesm** [comment]
cpplint failure

**Comment by wesm** [comment]
This is super odd BTW, I am not sure where the test failure on the Arrow side was introduced

**Comment by wesm** [comment]
Is this good when the build runs? You should enable appveyor on your fork if you haven't already

**Comment by cpcloud** [comment]
Yep, as soon as the appveyor build is green this is ready to merge.

**Comment by cpcloud** [comment]
Running on my fork here: https://ci.appveyor.com/project/cpcloud/parquet-cpp

**Comment by cpcloud** [comment]
Actually, let me add a test that exercises actual file metadata instead of the somewhat contrived schema based test I have here.

**Comment by cpcloud** [comment]
Ah, I'm actually doing that already :) This ready to go as soon as appveyor passes.

**Comment by cpcloud** [comment]
@wesm This is passing here: https://ci.appveyor.com/project/cpcloud/parquet-cpp/build/1.0.2

**Comment by wesm** [comment]
This patch broke coveralls

**Comment by wesm** [comment]
https://coveralls.io/repos/93701/builds?page=12

**Comment by cpcloud** [comment]
Hm, I remember failing CI without that hack.

**Comment by cpcloud** [comment]
I'll revert that commit and see if it still fails.

**Pull request closed without merging**
