### PR TITLE
PARQUET-1148: Revert coverage changes from PARQUET-1038

### PR DESCRIPTION
**Pull request by wesm**
Will take a look to see if this fixes the coverage upload

cc @cpcloud

### CODE REVIEW

**Comment by cpcloud** [comment]
@wesm Thanks for doing this.

Are lines like these concerning?

```
File '/usr/include/c++/4.9/istream'
No executable lines
Removing 'decode_benchmark.cc.o##istream.gcov'
```

My original goal with that patch was to prevent coverage of `std`.

**Comment by wesm** [comment]
Yeah, you can see in this build on June 22 that things are pretty messed up:

https://coveralls.io/builds/12088976

It seems things are broken in numerous ways. After the changes in #357 coveralls no longer recognized anything from the coverage upload

**Comment by wesm** [comment]
Alright with the patch in the current state, nothing is showing up: https://coveralls.io/jobs/30578926

**Comment by wesm** [comment]
It looks like coveralls-lcov might save us here, since cpp_coveralls is super fickle. see example project:

https://github.com/kimkulling/openddl-parser/blob/master/.travis.yml

**Comment by wesm** [comment]
Closing. If we proceed with the monorepo initiative, then coverage will be taken care of pretty much automatically

**Pull request closed without merging**
