### PR TITLE
PARQUET-449: updated to latest parquet.thrift

### PR DESCRIPTION
**Pull request by kashif**

### CODE REVIEW

**Comment by kashif** [comment]
@wesm can you kindly have a look?

**Comment by wesm** [comment]
Looks good, thank you! Will leave to @nongli to merge

**Comment by wesm** [comment]
@kashif can you try to fix the build or else roll back to Thrift 0.9.1 (and regenerate the bindings using the 0.9.1 compiler)?

**Comment by kashif** [comment]
yes sure @wesm looking into why it doesn't build on linux...

**Comment by wesm** [comment]
It seems that removing the `make clean` in `build_thirdparty.sh` might fix the issue, if you want to give that a shot. 

https://issues.apache.org/jira/browse/THRIFT-3274

**Comment by wesm** [comment]
Cool that worked!

**Comment by julienledem** [comment]
LGTM. +1
We should figure out a good way to depend on the central thrift version.

**Comment by nongli** [comment]
Can you rename the PR title to "Parquet-449: ..." (No brackets)? This is consistent with parquet-mr and the tool we use to merge enforces this. I think you can just do this in github.

**Comment by kashif** [comment]
@nongli done

**Comment by nongli** [comment]
@kashif Thanks! merged.

**Comment by wesm** [comment]
@julienledem I created a JIRA about this https://issues.apache.org/jira/browse/PARQUET-466

**Comment by wesm** [comment]
I was bummed to find that we now require Thrift 0.9.3 to compile the thrift headers. Perhaps we can add an option to generate them with the active thrift compiler to be less burdensome. However, Thrift 0.9.3 has better cross-platform portability so this will probably be needed to make this library work on MSVC

**Comment by wesm** [comment]
https://issues.apache.org/jira/browse/PARQUET-468

**Pull request closed without merging**
