### PR TITLE
[PARQUET-1004] Building fails on windows with PARQUET_ZLIB_VENDORED is turned on

### PR DESCRIPTION
**Pull request by atkawa7**

### CODE REVIEW

**Comment by wesm** [comment]
Is this issue not addressed by the `ZLIB_MSVC_STATIC_LIB_SUFFIX` CMake option?

**Comment by atkawa7** [comment]
@wesm Thanks.  I didn't see that option. It  would be great if that is added to the docs

**Comment by wesm** [comment]
@MaxRis could you add a note to the README/build instructions about this?

**Comment by MaxRis** [comment]
@wesm , sure, here it's [PR](https://github.com/apache/parquet-cpp/pull/345)

**Pull request closed without merging**
