### PR TITLE
PARQUET-739: Don't use a static buffer for data accessed by multiple threads

### PR DESCRIPTION
**Pull request by majetideepak**
I am hitting this problem at another location too.

### CODE REVIEW

**Comment by wesm** [comment]
+1

**Comment by wesm** [comment]
Would be nice to test this kind of stuff at some point, but may be difficult to make test failures reproducible

**Comment by majetideepak** [comment]
Yeah! Reproducibility is an issue. This bug surfaced when loading lots of data.
We could use static code analyzers that might help us uncover such bugs.

**Comment by flode** [comment]
Running helgrind in some automated way could help, it detects when there's a data race problem. That makes reproducing easier as it doesn't need to crash to be detected

**Pull request closed without merging**
