### PR TITLE
PARQUET-981: Resolve Windows build issues with 3rd party libs referen…

### PR DESCRIPTION
**Pull request by MaxRis**
…ced by *_HOME variables

### CODE REVIEW

**Comment by wesm** [comment]
Missed some things in this review. This broke the Arrow build https://travis-ci.org/apache/arrow/jobs/232424614 so will need to be fixed ASAP

**Comment by wesm** [comment]
Not completely sure, we are still investigating

**Comment by MaxRis** [comment]
`No rule to make target `/home/travis/build/apache/arrow/parquet-env/lib/libzlibstatic.a` I have changed FindZLIB.cmake related to this, going to check

**Comment by MaxRis** [comment]
@wesm , will create PR with fix in few minutes

**Pull request closed without merging**
