### PR TITLE
PARQUET-468: Use thirdparty Thrift compiler to compile parquet.thrift at make time

### PR DESCRIPTION
**Pull request by wesm**
This also adds a `#define` working around the googletest incompatibility described in PARQUET-470.

### CODE REVIEW

**Comment by wesm** [comment]
@asandryh @majetideepak can you take a look? This can be merged after PARQUET-471

**Comment by wesm** [comment]
rebased

**Comment by majetideepak** [comment]
+1 LGTM

**Comment by majetideepak** [comment]
Were you able to verify if the fix for Thrift 0.9.3 works with this patch ?

**Comment by wesm** [comment]
I was able to build and run the test suite locally on Thrift 0.9.3. We could upgrade the dev sandbox to use 0.9.3 or leave it at 0.9.1, I don't have a strong opinion

**Comment by majetideepak** [comment]
Cool! Let's leave it at 0.9.1 for the first release. We can upgrade later.

**Comment by wesm** [comment]
thank you!

**Pull request closed without merging**
