### PR TITLE
PARQUET-662: Compile ParquetException implementation and explicitly export

### PR DESCRIPTION
**Pull request by wesm**
This was causing downstream failure in ARROW-237. Now thirdparty libraries can safely throw `ParquetException` and be properly recognized on both ends.

### CODE REVIEW

**Comment by wesm** [comment]
I verified locally that this resolves the downstream failure on OS X.

**Comment by wesm** [comment]
I added a simple option to `ADD_PARQUET_TEST` so we can write unit tests against the shared library (defaults to the static library).

**Comment by nongli** [comment]
+1

**Comment by wesm** [comment]
Thanks. I cleaned up the cmake function a bit and will merge on green build.

**Comment by majetideepak** [comment]
+1 LGTM

**Pull request closed without merging**
