### PR TITLE
PARQUET-537: Ensure that LocalFileSource is properly closed.

### PR DESCRIPTION
**Pull request by asandryh**

### CODE REVIEW

**Comment by wesm** [comment]
Unit test please.

**Comment by asandryh** [comment]
Not sure what a unit test in this case will look like. I've just added explicit closing of sources in dtors.

**Comment by wesm** [comment]
Examine the file descriptor after invoking the dtor -- you can use `fcntl` to see if it is still open http://man7.org/linux/man-pages/man2/fcntl.2.html

**Comment by wesm** [comment]
I would just use `alltypes_plain.parquet` for this -- the test case can get refactored later to work on files that we generate using parquet-cpp

**Comment by asandryh** [comment]
@wesm I've added a unit test. Please take a look.

**Comment by julienledem** [comment]
+1

**Pull request closed without merging**
