### PR TITLE
PARQUET-497: Decouple serialized file internals from the ParquetFileReader public API

### PR DESCRIPTION
**Pull request by wesm**
This depends on PARQUET-501. A bit of a refactoring bloodbath, but extremely important to split out these details so that we can instrument the file reader public APIs with test fixtures for unit testing purposes.

### CODE REVIEW

**Comment by wesm** [comment]
Rebased.

**Comment by julienledem** [comment]
+1

**Comment by julienledem** [comment]
Ah, it needs to be rebased again. Sorry

**Comment by wesm** [comment]
No problem. Just a few minutes

**Comment by wesm** [comment]
@julienledem rebased. thank you sir

**Pull request closed without merging**
