### PR TITLE
PARQUET-813: Build thirdparty dependencies using ExternalProject

### PR DESCRIPTION
**Pull request by xhochy**

### CODE REVIEW

**Comment by majetideepak** [comment]
+1 LGTM

**Comment by xhochy** [comment]
Last Build failure was due to a race in the Arrow build process. Will need to fix this first.

**Comment by wesm** [comment]
We need to do some more work on the README, and add details about customizing the thirdparty toolchain

**Comment by wesm** [comment]
The Brotli download is so painful. I wonder what's the ETA on Brotli 0.6.0?

**Comment by wesm** [comment]
I did some README cleanup in #210

**Comment by xhochy** [comment]
Brotli is in prepartion for 1.0.0 https://github.com/google/brotli/issues/483

**Pull request closed without merging**
