### PR TITLE
PARQUET-709: Fix conda dev artifact builds

### PR DESCRIPTION
**Pull request by wesm**

### CODE REVIEW

**Comment by wesm** [comment]
We're back in business again whenever someone can give their +1

**Comment by majetideepak** [comment]
+1

**Comment by xhochy** [comment]
+1

**Comment by xhochy** [comment]
@wesm Took this as my first merge. Hopefully everything worked as expected.

**Comment by julienledem** [comment]
@xhochy looks good. Congrats on your first commit!

**Pull request closed without merging**
