### PR TITLE
PARQUET-918: Keep ordering in column indices when converting Parquet Schema

### PR DESCRIPTION
**Pull request by advancedxy**
This is a follow up fix for [PARQUET-918](https://github.com/apache/parquet-cpp/pull/295), do I need to create another jira for this?

Looks like some .idea files are included by accident. It looks no harm. Do I need to revert them?@wesm 

cc @wesm @itaiin  for reviewing

### CODE REVIEW

**Comment by wesm** [comment]
Can you remove the .idea files? Feel free to add .idea to .gitignore. Please add "PARQUET-918" to the start of the PR title, too

Would you mind also running `make format` if you have LLVM 3.9 / clang-format-3.9 installed?

**Comment by advancedxy** [comment]
Will revert .idea files.

I tried to run `make format`.
Looks like there are some other style issues regard for my modification. 

Should I also commit these changes?

**Comment by advancedxy** [comment]
Done and ready for review. Other style changes are remained as it is.

**Comment by wesm** [comment]
Thanks. What version of LLVM do you have?

**Comment by advancedxy** [comment]
Latest version from HomeBrew，didn't realize 3.9 is mandatory.

**Comment by wesm** [comment]
looks like Homebrew moved to 4.0 last month

https://github.com/Homebrew/homebrew-core/commit/a41058cd0e516d1bd026d32e781ec262a83d5a67#diff-194f104361b709d20f88c66fcc785e83

That's pretty aggressive considering 3.9 is considered the stable release per http://apt.llvm.org/

**Pull request closed without merging**
