### PR TITLE
PARQUET-600: Add benchmarks for RLE-Level encoding

### PR DESCRIPTION
**Pull request by xhochy**

### CODE REVIEW

**Comment by xhochy** [comment]
I was surprised to see decoding to be a bit slower then encoding. These benchmarks reveal one of the major bottlenecks:

```
Run on (1 X 3411.48 MHz CPU )
2016-05-04 19:44:33
Benchmark             Time(ns)    CPU(ns) Iterations
----------------------------------------------------
BM_RleEncoding/1024       1753       1739     404213  1123.37MB/s
BM_RleEncoding/4k         6657       6642     105385  1.14857GB/s
BM_RleEncoding/32k       53693      53197      13125  1.14734GB/s
BM_RleEncoding/64k      106356     106124       6595  1.15026GB/s
BM_RleDecoding/1024       7827       7758      91393  251.765MB/s
BM_RleDecoding/4k        30760      30509      22913   256.07MB/s
BM_RleDecoding/32k      249988     249419       2817  250.582MB/s
BM_RleDecoding/64k      497735     497565       1410  251.224MB/s
```

**Comment by wesm** [comment]
From the look of the decode path, there's quite a bit of batching / optimization work that would be done there. `BitReader::GetValue<T>` might be worth a look

**Comment by wesm** [comment]
Everything else is merged, just ping me when you want to merge this. thanks!

**Comment by xhochy** [comment]
Integrated the formula from PARQUET-599 so it's now ready to be merged.

**Comment by wesm** [comment]
+1, thank you

**Pull request closed without merging**
