### PR TITLE
PARQUET-1267: [C++] replace "unsafe" std::equal by std::memcmp

### PR DESCRIPTION
**Pull request by rip-nsk**

### CODE REVIEW

**Comment by jbapple-cloudera** [comment]
What's the actual text of the warning?

**Comment by rip-nsk** [comment]
'std::equal::_Unchecked_iterators::_Deprecate': Call to 'std::equal' with parameters that may be unsafe - this call relies on the caller to check that the passed values are correct.

**Comment by jbapple-cloudera** [comment]
How is `memcmp` any safer? This sounds like an issue with the compiler, rather than the code.

**Comment by rip-nsk** [comment]
std::memcmp is not safer, it just requires the same size arguments.
std::equal has (implicitly) the same requirements, but since c++14 introduces a more secure version, this one is marked as deprecate.
Both variants are valid (since we check size of arrays first).

**Pull request closed without merging**
