### PR TITLE
PARQUET-1104: Upgrade to Apache Arrow 0.7.0 RC0

### PR DESCRIPTION
**Pull request by wesm**
This will enable most of the outstanding PRs to be rebased and then merged

Close #384 
Close #394

### CODE REVIEW

**Comment by wesm** [comment]
Cherry-picked PARQUET-1082 since it's a required fix

**Comment by wesm** [comment]
@majetideepak I included a fix for the boost_system issue. I remember you mentioned this, but I'd been too busy to investigate. Can you definitely bug us very loudly when you run into a new transitive dependency? I would rather have fixed this before cutting the Arrow 0.7.0 RC but it's not a big enough problem to cancel the release over.

**Comment by majetideepak** [comment]
@wesm  Will be very loud next time. Can we revert the  boost_system dependency in the next release?

**Comment by wesm** [comment]
I created https://issues.apache.org/jira/browse/ARROW-1536 about fixing that, yes

**Comment by majetideepak** [comment]
Filed PARQUET-1105 on the Parquet side to track it.

**Pull request closed without merging**
