### PR TITLE
PARQUET-513: Fail build if valgrind finds error during ctest, fix a core dump

### PR DESCRIPTION
**Pull request by wesm**
Also adds an option to use ccache with a custom gcc toolchain. 

Fixes an improper memory access stemming from a unit test that had a wrong parameter.

### CODE REVIEW

**Comment by wesm** [comment]
The b46c617 build should fail (if this .travis.yml fix worked) while 43df9e7 should pass (because I fixed the core dump).

**Comment by wesm** [comment]
Argh, non-deterministic behavior! Well, this patch can be merged if you are satisfied with the fix.

**Comment by asandryh** [comment]
Where do you observe non-deterministic behavior?

**Comment by wesm** [comment]
In the first commit I have valgrind errors locally but they did not occur on Travis CI

**Comment by asandryh** [comment]
+1. LGTM

**Comment by wesm** [comment]
thank you!

**Pull request closed without merging**
