### PR TITLE
PARQUET-900: Fix NOTICE / LICENSE issues

### PR DESCRIPTION
**Pull request by xhochy**
@rdblue Can you check that this resolves all issues from the RC3?

### CODE REVIEW

**Comment by rdblue** [comment]
Looks like it fixes the issues I saw. You can also run the release audit tool:

```
bash dev/release/run-rat.sh .
```

**Comment by xhochy** [comment]
Will do later, currently the ASF mirrors don't provide me with a valid version of the JAR (i.e. I currently get HTTP 503 responses)

**Comment by rdblue** [comment]
Maybe it is affected by the S3 outage

**Comment by xhochy** [comment]
Green build https://travis-ci.org/xhochy/parquet-cpp/builds/207315682

**Pull request closed without merging**
