### PR TITLE
PARQUET-767: Add release scripts

### PR DESCRIPTION
**Pull request by xhochy**
Based on the release scripts from Apache Aurora (as we don't have the luxury of the Maven release plugin, we need a bit more code). Kudos to @StephanErb for pointing me to them.

- [x] Rename JIRA release tag from `cpp-0.1` to `cpp-0.1.0` ( @julienledem can you take care of this?) This is then in line with all other Apache Parquet artifacts.
- [x] Test the scripts with dry-run mode (needs the above point)
- [x] Reference Apache Aurora in LICENSE/NOTICE
- [x] Add Guides
- [x] Add script to verify the release

### CODE REVIEW

**Comment by wesm** [comment]
@xhochy I just renamed the JIRA release tag. We still need to reference Impala in the LICENSE

**Comment by xhochy** [comment]
As a sidenote: The fixed Travis image will be released somewhere in the next ~12h, then we are hopefully back to green Parquet builds.

**Comment by StephanErb** [comment]
I would recommend to also include a short documentation how to use the scripts. Here are the docs we have been using so far: https://github.com/apache/aurora/blob/master/docs/development/committers-guide.md#creating-a-release

**Comment by xhochy** [comment]
That's the TODO `Add Guides` above ;)

**Comment by wesm** [comment]
+1. It's kind of an unbelievable amount of code

**Pull request closed without merging**
