### PR TITLE
PARQUET-1402: [C++] parquet-mr writes dictionary_page_offset == 0 when it is (supposed?) …

### PR DESCRIPTION
**Pull request by rip-nsk**
…equal to data_page_offset.

### CODE REVIEW

**Comment by xhochy** [comment]
Can you add a test for this?

**Comment by rip-nsk** [comment]
I don't have data file suitable for test.

**Comment by rip-nsk** [comment]
[test.parquet](https://issues.apache.org/jira/secure/attachment/12937186/test.parquet) to reproduce issue/verify fix.
I can't find suitable place for test after quick look into source tree..

**Comment by rip-nsk** [comment]
It is attached to [https://issues.apache.org/jira/browse/PARQUET-1402](https://issues.apache.org/jira/browse/PARQUET-1402)

**Comment by wesm** [comment]
This PR needs to be moved to https://github.com/apache/arrow -- please let us know if you require assistance

**Comment by wesm** [comment]
Hi, can we get this PR moved over?

**Pull request closed without merging**
