### PR TITLE
PARQUET-653: Build conda artifacts with -static-libstdc++ again

### PR DESCRIPTION
**Pull request by wesm**
The final stage of this work will be to move dev/testing packaging builds to centos6 images on Circle CI (this may be possible in Travis -- which allows you to use docker -- but easier with Circle CI)

### CODE REVIEW

**Comment by xhochy** [comment]
+1, LGTM

**Comment by wesm** [comment]
+1, thanks

**Comment by wesm** [comment]
So, this unfortunately has broken the Arrow builds. I think we're going to have to set up a separate repo with a Dockerfile that uses the RHEL devtoolset to build these artifacts. static linking libstdc++ is far too finicky it turns out

**Comment by wesm** [comment]
We could also just use conda forge and keep bumping the build number when we're ready to upgrade the artifact

**Pull request closed without merging**
