### PR TITLE
PARQUET-1074: Use long key ids in KEYS file

### PR DESCRIPTION
**Pull request by lekv**
Created like so: gpg --import < KEYS 2>&1 | grep key | awk '{print $3}'
| tr -d ':' | while read k; do gpg --list-sigs --keyid-format long $k;
gpg --export --armor $k; done > newkeys

### CODE REVIEW

**Comment by lekv** [comment]
Let me know what you think. If this is something we want to change I'll go ahead and create a JIRA.

**Comment by xhochy** [comment]
I would be fine with this change but I'm a bit confused why the public keys changed. Is there any simple explanation for this?

**Comment by lekv** [comment]
The shell one-liner seems to have split Alex's two keys into two separate blocks (because it exported by key, not by email address). I can try to fix that.

Your key seems to have gotten two more signatures since you added it. You can inspect them like so: diff <(gpg --list-packets < ~/src/parquet-cpp/apache-parquet-cpp-1.2.0/KEYS) <(gpg --list-packets ~/checkout/parquet-cpp/newkeys)

**Comment by xhochy** [comment]
Build is broken because of https://issues.apache.org/jira/browse/PARQUET-1075

**Comment by xhochy** [comment]
Also updated the KEYS file in SVN.

@lekv we might also need to update the KEYS file in parquet-format git

**Comment by lekv** [comment]
@xhochy Thanks for taking care of SVN. I didn't know it even existed. Maybe it'd be best to copy the same file to all projects and leave a KEYS.README to explain how to make changes, e.g. change in one project, copy to SVN, copy to all other projects) to keep them in sync?

**Pull request closed without merging**
